package eubos.position;

import static org.junit.Assert.*;

import java.util.List;

import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;

import com.fluxchess.jcpi.models.GenericMove;
import com.fluxchess.jcpi.models.IllegalNotationException;


import eubos.board.Piece;

public class CastlingManagerTest {

	protected CastlingManager classUnderTest;
	private PositionManager pm;
	private MoveList ml; 
	
	@Before
	public void setUp() {
	}
	
	void setupPosition(String fen)  {
		pm = new PositionManager(fen);
		ml = new MoveList(pm, 0);
		ml.initialiseAtPly(Move.NULL_MOVE, null, false, false, 0);
		ml.getNextMovesAtPly(0);
	}
	
	@Test
	public void test_WhiteKingSideCastle() throws IllegalNotationException  {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ....k..r
		//   abcdefgh
		setupPosition("8/8/8/8/8/8/8/4K2R w K - - -");
		expectWkscMove();
	}
	
	@Test
	public void test_WhiteKingSideCastle_whenRookMoved() throws IllegalNotationException {
		// 8 k.......
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ....K..R
		//   abcdefgh
		setupPosition("k7/8/8/8/8/8/8/4K2R w K - - 1");
		pm.performMove(Move.toMove(new GenericMove("h1h2"), pm.getTheBoard()));
		pm.performMove(Move.toMove(new GenericMove("a8b8"), pm.getTheBoard()));
		pm.performMove(Move.toMove(new GenericMove("h2h1"), pm.getTheBoard()));
		pm.performMove(Move.toMove(new GenericMove("b8a8"), pm.getTheBoard()));
		classUnderTest = pm.castling;
		ml = new MoveList(pm, 0);
		ml.initialiseAtPly(Move.NULL_MOVE, null, false, false, 0);
		ml.getNextMovesAtPly(0);
		classUnderTest.addCastlingMoves(Piece.Colour.isWhite(pm.getOnMove()), ml.ma_quietNoKillers);
		List<Integer> moves = ml.getList();
		assertFalse(moves.contains(CastlingManager.wqsc));
		assertFalse(moves.contains(CastlingManager.wksc));
	}
	
	@Test
	public void test_WhiteKingSideCastle_whenKingMoved() throws IllegalNotationException {
		// 8 k.......
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ....K..R
		//   abcdefgh
		setupPosition("k7/8/8/8/8/8/8/4K2R w K - - 1");
		pm.performMove(Move.valueOf(Position.e1, Piece.WHITE_KING, Position.e2, Piece.NONE));
		pm.performMove(Move.valueOf(Position.a8, Piece.BLACK_KING, Position.b8, Piece.NONE));
		pm.performMove(Move.valueOf(Position.e2, Piece.WHITE_KING, Position.e1, Piece.NONE));
		pm.performMove(Move.valueOf(Position.b8, Piece.BLACK_KING, Position.a8, Piece.NONE));
		classUnderTest = pm.castling;	
		ml = new MoveList(pm, 0);
		ml.initialiseAtPly(Move.NULL_MOVE, null, false, false, 0);
		ml.getNextMovesAtPly(0);
		classUnderTest.addCastlingMoves(Piece.Colour.isWhite(pm.getOnMove()), ml.ma_quietNoKillers);
		List<Integer> moves = ml.getList();
		assertFalse(moves.contains(CastlingManager.wqsc));
		assertFalse(moves.contains(CastlingManager.wksc));
	}	
	
	@Test
	public void test_wksc_fen_unavaill() throws IllegalNotationException {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ....k..r
		//   abcdefgh
		setupPosition("8/8/8/8/8/8/8/4K2R w k - - -");
		classUnderTest = pm.castling;
		classUnderTest.addCastlingMoves(Piece.Colour.isWhite(pm.getOnMove()), ml.ma_quietNoKillers);
		List<Integer> moves = ml.getList();
		assertFalse(moves.contains(CastlingManager.wqsc));
		assertFalse(moves.contains(CastlingManager.wksc));
	}
	
	@Test
	@Ignore // As when the king is in check, the castling manager is not called
	public void test_WhiteKingSideCastle_Check() throws IllegalNotationException  {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ..B.....
		// 2 ........
		// 1 ....k..r
		//   abcdefgh
		setupPosition("8/8/8/8/8/2b5/8/4K2R w K - - -");
		classUnderTest = pm.castling;
		classUnderTest.addCastlingMoves(Piece.Colour.isWhite(pm.getOnMove()), ml.ma_quietNoKillers);
		assertFalse(ml.getList().contains(CastlingManager.wqsc));
		assertFalse(ml.getList().contains(CastlingManager.wksc));
	}
	
	@Test
	public void test_WhiteKingSideCastle_MovesThroughCheckAtF1()  {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ...B....
		// 2 ........
		// 1 ....k..r
		//   abcdefgh
		setupPosition("8/8/8/8/8/3b4/8/4K2R w K - - -");
		classUnderTest = pm.castling;
		classUnderTest.addCastlingMoves(Piece.Colour.isWhite(pm.getOnMove()), ml.ma_quietNoKillers);
		List<Integer> moves = ml.getList();
		assertFalse(moves.contains(CastlingManager.wqsc));
		assertFalse(moves.contains(CastlingManager.wksc));
	}
	
	@Test
	public void test_WhiteKingSideCastle_MovesThroughCheckAtG1() {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ....B...
		// 2 ........
		// 1 ....k..r
		//   abcdefgh
		setupPosition("8/8/8/8/8/4b3/8/4K2R w K - - -");
		classUnderTest = pm.castling;
		classUnderTest.addCastlingMoves(Piece.Colour.isWhite(pm.getOnMove()), ml.ma_quietNoKillers);
		List<Integer> moves = ml.getList();
		assertFalse(moves.contains(CastlingManager.wqsc));
		assertFalse(moves.contains(CastlingManager.wksc));
	}
	
	@Test
	public void test_WhiteKingSideCastle_BlockedOwnPieceAtF1()  {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ....kb.r
		//   abcdefgh
		setupPosition("8/8/8/8/8/8/8/4KB1R w K - - -");
		classUnderTest = pm.castling;
		classUnderTest.addCastlingMoves(Piece.Colour.isWhite(pm.getOnMove()), ml.ma_quietNoKillers);
		List<Integer> moves = ml.getList();
		assertFalse(moves.contains(CastlingManager.wqsc));
		assertFalse(moves.contains(CastlingManager.wksc));
	}
	
	@Test
	public void test_WhiteKingSideCastle_BlockedOwnPieceAtG1()  {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ....k.br
		//   abcdefgh
		setupPosition("8/8/8/8/8/8/8/4K1BR w K - - -");
		classUnderTest = pm.castling;
		classUnderTest.addCastlingMoves(Piece.Colour.isWhite(pm.getOnMove()), ml.ma_quietNoKillers);
		List<Integer> moves = ml.getList();
		assertFalse(moves.contains(CastlingManager.wqsc));
		assertFalse(moves.contains(CastlingManager.wksc));
	}	
	
	@Test
	public void test_WhiteKingSideCastle_RookIsAttackedAtH1() throws IllegalNotationException  {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 .....B..
		// 2 ........
		// 1 ....k..r
		//   abcdefgh
		setupPosition("8/8/8/8/8/5b2/8/4K2R w K - - -");
		expectWkscMove();
	}

	@Test
	public void test_BlackQueenSideCastle() throws IllegalNotationException   {
		// 8 R...K...
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		setupPosition("r3k3/8/8/8/8/8/8/8 b q - - -");
		expectBqscMove();
	}
	
	@Test
	@Ignore // As when the king is in check, the castling manager is not called
	public void test_BlackQueenSideCastle_Check()  {
		// 8 R...K...
		// 7 ........
		// 6 ......b.
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		setupPosition("r3k3/8/6B1/8/8/8/8/8 b q - - -");
		classUnderTest = pm.castling;
		classUnderTest.addCastlingMoves(Piece.Colour.isWhite(pm.getOnMove()), ml.ma_quietNoKillers);
		assertFalse(ml.getList().contains(CastlingManager.bqsc));
		assertFalse(ml.getList().contains(CastlingManager.bksc));
	}
	
	@Test
	public void test_bqsc_fen_unavaill()  {
		// 8 R...K...
		// 7 ........
		// 6 ......b.
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		setupPosition("r3k3/8/8/8/8/8/8/8 b Q - - -");
		classUnderTest = pm.castling;
		classUnderTest.addCastlingMoves(Piece.Colour.isWhite(pm.getOnMove()), ml.ma_quietNoKillers);
		List<Integer> moves = ml.getList();
		assertFalse(moves.contains(CastlingManager.bqsc));
		assertFalse(moves.contains(CastlingManager.bksc));
	}
	
	@Test
	public void test_bqsc_fen_availl() throws IllegalNotationException  {
		// 8 R...K...
		// 7 ........
		// 6 ......b.
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		setupPosition("r3k3/8/8/8/8/8/8/8 b q - - -");
		ml.initialiseAtPly(Move.NULL_MOVE, null, false, false, 0);
		assertTrue(ml.getList().contains(CastlingManager.bqsc));
		ml.initialiseAtPly(Move.NULL_MOVE, null, false, false, 0);
		assertFalse(ml.getList().contains(CastlingManager.bksc));
	}	
	
	@Test
	public void test_BlackQueenSideCastle_MovesThroughCheckAtD8()  {
		// 8 R...K...
		// 7 ........
		// 6 .....b..
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		setupPosition("r3k3/8/5B2/8/8/8/8/8 b q - - -");
		classUnderTest = pm.castling;
		classUnderTest.addCastlingMoves(Piece.Colour.isWhite(pm.getOnMove()), ml.ma_quietNoKillers);
		List<Integer> moves = ml.getList();
		assertFalse(moves.contains(CastlingManager.bqsc));
		assertFalse(moves.contains(CastlingManager.bksc));
	}
		
	@Test
	public void test_BlackQueenSideCastle_MovesThroughCheckAtC8()  {
		// 8 R...K...
		// 7 ........
		// 6 ....b...
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		setupPosition("r3k3/8/4B3/8/8/8/8/8 b q - - -");
		classUnderTest = pm.castling;
		classUnderTest.addCastlingMoves(Piece.Colour.isWhite(pm.getOnMove()), ml.ma_quietNoKillers);
		List<Integer> moves = ml.getList();
		assertFalse(moves.contains(CastlingManager.bqsc));
		assertFalse(moves.contains(CastlingManager.bksc));
	}
	
	@Test
	public void test_BlackQueenSideCastle_BlockedOwnPieceAtD8()  {
		// 8 R..QK...
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		setupPosition("r2qk3/8/8/8/8/8/8/8 b q - - -");
		classUnderTest = pm.castling;
		classUnderTest.addCastlingMoves(Piece.Colour.isWhite(pm.getOnMove()), ml.ma_quietNoKillers);
		List<Integer> moves = ml.getList();
		assertFalse(moves.contains(CastlingManager.bqsc));
		assertFalse(moves.contains(CastlingManager.bksc));
	}
	
	@Test
	public void test_BlackQueenSideCastle_RookIsAttackedAtA8() throws IllegalNotationException   {
		// 8 R...K...
		// 7 ........
		// 6 R.......
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		setupPosition("r3k3/8/R7/8/8/8/8/8 b q - - -");
		classUnderTest = pm.castling;
		classUnderTest.addCastlingMoves(Piece.Colour.isWhite(pm.getOnMove()), ml.ma_quietNoKillers);
		ml.initialiseAtPly(Move.NULL_MOVE, null, false, false, 0);
		assertTrue(ml.getList().contains(CastlingManager.bqsc));
		ml.initialiseAtPly(Move.NULL_MOVE, null, false, false, 0);
		assertFalse(ml.getList().contains(CastlingManager.bksc));
	}
	
	@Test
	public void test_WhiteKingSideCastle_fromgame() throws IllegalNotationException   {
		pm = new PositionManager("rnb2bnr/1ppp1kpp/4pq2/8/p1BPP3/8/PPP2PPP/RNBQK2R w KQ - 1 7");
		ml = new MoveList(pm, 0);
		ml.initialiseAtPly(Move.NULL_MOVE, null, false, false, 0);
		ml.getNextMovesAtPly(0);
		ml.getNextMovesAtPly(0);
		classUnderTest = pm.castling;
		classUnderTest.addCastlingMoves(Piece.Colour.isWhite(pm.getOnMove()), ml.ma_quietNoKillers);
		expectWkscMove();
	}

	private void expectBqscMove() throws IllegalNotationException {
		ml.initialiseAtPly(Move.NULL_MOVE, null, false, false, 0);
		assertTrue(ml.getList().contains(CastlingManager.bqsc));
	}
	
	private void expectWkscMove() throws IllegalNotationException {
		ml.initialiseAtPly(Move.NULL_MOVE, null, false, false, 0);
		assertTrue(ml.getList().contains(CastlingManager.wksc));
	}
}
