package eubos.board;

import java.util.LinkedList;

import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import eubos.pieces.Bishop;
import eubos.pieces.King;
import eubos.pieces.Pawn;
import eubos.pieces.Piece;
import eubos.pieces.Queen;
import eubos.pieces.Rook;
import eubos.pieces.Piece.Colour;

import com.fluxchess.jcpi.models.GenericPosition;
import com.fluxchess.jcpi.models.GenericMove;
import com.fluxchess.jcpi.models.GenericChessman;

public class BoardManagerTest {
	
	protected LinkedList<Piece> pl;
	protected BoardManager classUnderTest;
	
	@Before
	public void setUp() {
		pl = new LinkedList<Piece>();
	}
	
	@Test
	public void test_NoLastMoveToUndo() throws InvalidPieceException {
		classUnderTest = new BoardManager();
		classUnderTest.undoPreviousMove();
	}
	
	@Test
	public void test_UndoPawnMove() throws InvalidPieceException {
		pl.add( new Pawn( Piece.Colour.white, GenericPosition.e2 ));
		classUnderTest = new BoardManager( new Board( pl ), Colour.white );
		classUnderTest.performMove( new GenericMove( GenericPosition.e2, GenericPosition.e4 ));
		classUnderTest.undoPreviousMove();
		Piece expectPawn = classUnderTest.getTheBoard().getPieceAtSquare( GenericPosition.e2 );
		assertTrue( expectPawn instanceof Pawn );
		assertTrue( expectPawn.isWhite());		
	}
	
	@Test
	public void test_UndoPawnPromotion() throws InvalidPieceException {
		pl.add( new Pawn( Piece.Colour.black, GenericPosition.e2 ));
		classUnderTest = new BoardManager( new Board( pl ), Colour.black );
		classUnderTest.performMove( new GenericMove( GenericPosition.e2, GenericPosition.e1, GenericChessman.QUEEN ));
		classUnderTest.undoPreviousMove();
		Piece expectPawn = classUnderTest.getTheBoard().getPieceAtSquare( GenericPosition.e2 );
		assertTrue( expectPawn instanceof Pawn );
		assertTrue( expectPawn.isBlack());
	}
	
	@Test
	public void test_UndoPawnCapture() throws InvalidPieceException {
		pl.add( new Pawn( Piece.Colour.black, GenericPosition.d3 ));
		pl.add( new Pawn( Piece.Colour.white, GenericPosition.e2 ));
		classUnderTest = new BoardManager( new Board( pl ), Colour.white );
		classUnderTest.performMove( new GenericMove( GenericPosition.d3, GenericPosition.e2 ));
		classUnderTest.undoPreviousMove();
		Piece expectPawn = classUnderTest.getTheBoard().getPieceAtSquare( GenericPosition.d3 );
		assertTrue( expectPawn instanceof Pawn );
		assertTrue( expectPawn.isBlack());
		expectPawn = classUnderTest.getTheBoard().getPieceAtSquare( GenericPosition.e2 );
		assertTrue( expectPawn instanceof Pawn );
		assertTrue( expectPawn.isWhite());
	}
	
	@Test
	public void test_WhiteKingSideCastle() {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ....k..r
		//   abcdefgh
		classUnderTest = new BoardManager("8/8/8/8/8/8/8/4K2R w - - - -");
		GenericMove kscMove = classUnderTest.addKingSideCastle();
		GenericMove expectedMove = new GenericMove( GenericPosition.e1, GenericPosition.g1 );
		assertTrue(kscMove != null);
		assertTrue(expectedMove.equals(kscMove));
	}
	
	@Test
	public void test_WhiteKingSideCastle_performMove() throws InvalidPieceException {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ....k..r
		//   abcdefgh
		classUnderTest = new BoardManager("8/8/8/8/8/8/8/4K2R w - - - -");
		GenericMove expectedMove = new GenericMove( GenericPosition.e1, GenericPosition.g1 );
		classUnderTest.performMove(expectedMove);
		Piece whiteRook = classUnderTest.getTheBoard().getPieceAtSquare(GenericPosition.h1);
		assertTrue(whiteRook == null);
		whiteRook = classUnderTest.getTheBoard().getPieceAtSquare(GenericPosition.f1);
		assertTrue(whiteRook instanceof Rook);
		assertTrue(classUnderTest.isWhiteHasCastled());
	}
	
	@Test
	public void test_WhiteKingSideCastle_unperformMove() throws InvalidPieceException {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ....k..r
		//   abcdefgh
		classUnderTest = new BoardManager("8/8/8/8/8/8/8/4K2R w - - - -");
		GenericMove expectedMove = new GenericMove( GenericPosition.e1, GenericPosition.g1 );
		classUnderTest.performMove(expectedMove);
		Piece whiteRook = classUnderTest.getTheBoard().getPieceAtSquare(GenericPosition.h1);
		assertTrue(whiteRook == null);
		whiteRook = classUnderTest.getTheBoard().getPieceAtSquare(GenericPosition.f1);
		assertTrue(whiteRook instanceof Rook);
		classUnderTest.undoPreviousMove();
		whiteRook = classUnderTest.getTheBoard().getPieceAtSquare(GenericPosition.f1);
		assertTrue(whiteRook == null);
		whiteRook = classUnderTest.getTheBoard().getPieceAtSquare(GenericPosition.h1);
		assertTrue(whiteRook instanceof Rook);
		Piece whiteKing = classUnderTest.getTheBoard().getPieceAtSquare(GenericPosition.e1);
		assertTrue(whiteKing instanceof King);
		assertFalse(classUnderTest.isWhiteHasCastled());
	}	
	
	@Test
	public void test_WhiteKingSideCastle_Check() {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ..B.....
		// 2 ........
		// 1 ....k..r
		//   abcdefgh
		classUnderTest = new BoardManager("8/8/8/8/8/2b5/8/4K2R w - - - -");
		GenericMove kscMove = classUnderTest.addKingSideCastle();
		assertTrue(kscMove == null);
	}
	
	@Test
	public void test_WhiteKingSideCastle_MovesThroughCheckAtF1() {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ...B....
		// 2 ........
		// 1 ....k..r
		//   abcdefgh
		classUnderTest = new BoardManager("8/8/8/8/8/3b4/8/4K2R w - - - -");
		GenericMove kscMove = classUnderTest.addKingSideCastle();
		assertTrue(kscMove == null);
	}
	
	@Test
	public void test_WhiteKingSideCastle_MovesThroughCheckAtG1() {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ....B...
		// 2 ........
		// 1 ....k..r
		//   abcdefgh
		classUnderTest = new BoardManager("8/8/8/8/8/4b3/8/4K2R w - - - -");
		GenericMove kscMove = classUnderTest.addKingSideCastle();
		assertTrue(kscMove == null);
	}
	
	@Test
	public void test_WhiteKingSideCastle_BlockedOwnPieceAtF1() {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ....kb.r
		//   abcdefgh
		classUnderTest = new BoardManager("8/8/8/8/8/8/8/4KB1R w - - - -");
		GenericMove kscMove = classUnderTest.addKingSideCastle();
		assertTrue(kscMove == null);
	}
	
	@Test
	public void test_WhiteKingSideCastle_BlockedOwnPieceAtG1() {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ....k.br
		//   abcdefgh
		classUnderTest = new BoardManager("8/8/8/8/8/8/8/4K1BR w - - - -");
		GenericMove kscMove = classUnderTest.addKingSideCastle();
		assertTrue(kscMove == null);
	}	
	
	@Test
	public void test_WhiteKingSideCastle_RookIsAttackedAtH1() {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 .....B..
		// 2 ........
		// 1 ....k..r
		//   abcdefgh
		classUnderTest = new BoardManager("8/8/8/8/8/5b2/8/4K2R w - - - -");
		GenericMove kscMove = classUnderTest.addKingSideCastle();
		GenericMove expectedMove = new GenericMove( GenericPosition.e1, GenericPosition.g1 );
		assertTrue(kscMove != null);
		assertTrue(expectedMove.equals(kscMove));
	}
	
	
	@Test
	public void test_BlackQueenSideCastle() {
		// 8 R...K...
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		classUnderTest = new BoardManager("r3k3/8/8/8/8/8/8/8 b - - - -");
		GenericMove qscMove = classUnderTest.addQueenSideCastle();
		GenericMove expectedMove = new GenericMove( GenericPosition.e8, GenericPosition.c8 );
		assertTrue(qscMove != null);
		assertTrue(expectedMove.equals(qscMove));
	}
	
	@Test
	public void test_BlackQueenSideCastle_Check() {
		// 8 R...K...
		// 7 ........
		// 6 ......b.
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		classUnderTest = new BoardManager("r3k3/8/6B1/8/8/8/8/8 b - - - -");
		GenericMove qscMove = classUnderTest.addQueenSideCastle();
		assertTrue(qscMove == null);
	}
	
	@Test
	public void test_BlackQueenSideCastle_MovesThroughCheckAtD8() {
		// 8 R...K...
		// 7 ........
		// 6 .....b..
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		classUnderTest = new BoardManager("r3k3/8/5B2/8/8/8/8/8 b - - - -");
		GenericMove qscMove = classUnderTest.addQueenSideCastle();
		assertTrue(qscMove == null);
	}
		
	@Test
	public void test_BlackQueenSideCastle_MovesThroughCheckAtC8() {
		// 8 R...K...
		// 7 ........
		// 6 ....b...
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		classUnderTest = new BoardManager("r3k3/8/4B3/8/8/8/8/8 b - - - -");
		GenericMove qscMove = classUnderTest.addQueenSideCastle();
		assertTrue(qscMove == null);
	}
	
	@Test
	public void test_BlackQueenSideCastle_BlockedOwnPieceAtD8() {
		// 8 R..QK...
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		classUnderTest = new BoardManager("r2qk3/8/8/8/8/8/8/8 b - - - -");
		GenericMove qscMove = classUnderTest.addQueenSideCastle();
		assertTrue(qscMove == null);
	}
	
	@Test
	public void test_BlackQueenSideCastle_RookIsAttackedAtA8() {
		// 8 R...K...
		// 7 ........
		// 6 R.......
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		classUnderTest = new BoardManager("r3k3/8/R7/8/8/8/8/8 b - - - -");
		GenericMove qscMove = classUnderTest.addQueenSideCastle();
		GenericMove expectedMove = new GenericMove( GenericPosition.e8, GenericPosition.c8 );
		assertTrue(qscMove != null);
		assertTrue(expectedMove.equals(qscMove));
	}
}
