package eubos.board;

import static org.junit.Assert.*;

import java.util.LinkedList;

import org.junit.Before;
import org.junit.Test;

import com.fluxchess.jcpi.models.GenericMove;
import com.fluxchess.jcpi.models.IllegalNotationException;

public class CastlingManagerTest {

	protected CastlingManager classUnderTest;
	private LinkedList<GenericMove> ml; 
	
	@Before
	public void setUp() {
		ml = new LinkedList<GenericMove>();
	}
	
	@Test
	public void test_WhiteKingSideCastle() throws IllegalNotationException{
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ....k..r
		//   abcdefgh
		classUnderTest = new BoardManager("8/8/8/8/8/8/8/4K2R w K - - -").getCastlingManager();
		classUnderTest.addCastlingMoves(ml);
		expectWkscMove();
	}
	
	@Test
	public void test_wksc_fen_unavaill() throws IllegalNotationException{
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ....k..r
		//   abcdefgh
		classUnderTest = new BoardManager("8/8/8/8/8/8/8/4K2R w k - - -").getCastlingManager();
		classUnderTest.addCastlingMoves(ml);
		assertTrue(ml.isEmpty());
	}
	
	@Test
	public void test_WhiteKingSideCastle_Check() throws IllegalNotationException {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ..B.....
		// 2 ........
		// 1 ....k..r
		//   abcdefgh
		classUnderTest = new BoardManager("8/8/8/8/8/2b5/8/4K2R w K - - -").getCastlingManager();
		classUnderTest.addCastlingMoves(ml);
		assertTrue(ml.isEmpty());
	}
	
	@Test
	public void test_WhiteKingSideCastle_MovesThroughCheckAtF1() {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ...B....
		// 2 ........
		// 1 ....k..r
		//   abcdefgh
		classUnderTest = new BoardManager("8/8/8/8/8/3b4/8/4K2R w K - - -").getCastlingManager();
		classUnderTest.addCastlingMoves(ml);
		assertTrue(ml.isEmpty());
	}
	
	@Test
	public void test_WhiteKingSideCastle_MovesThroughCheckAtG1() {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ....B...
		// 2 ........
		// 1 ....k..r
		//   abcdefgh
		classUnderTest = new BoardManager("8/8/8/8/8/4b3/8/4K2R w K - - -").getCastlingManager();
		classUnderTest.addCastlingMoves(ml);
		assertTrue(ml.isEmpty());
	}
	
	@Test
	public void test_WhiteKingSideCastle_BlockedOwnPieceAtF1() {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ....kb.r
		//   abcdefgh
		classUnderTest = new BoardManager("8/8/8/8/8/8/8/4KB1R w K - - -").getCastlingManager();
		classUnderTest.addCastlingMoves(ml);
		assertTrue(ml.isEmpty());
	}
	
	@Test
	public void test_WhiteKingSideCastle_BlockedOwnPieceAtG1() {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ....k.br
		//   abcdefgh
		classUnderTest = new BoardManager("8/8/8/8/8/8/8/4K1BR w K - - -").getCastlingManager();
		classUnderTest.addCastlingMoves(ml);
		assertTrue(ml.isEmpty());
	}	
	
	@Test
	public void test_WhiteKingSideCastle_RookIsAttackedAtH1() throws IllegalNotationException {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 .....B..
		// 2 ........
		// 1 ....k..r
		//   abcdefgh
		classUnderTest = new BoardManager("8/8/8/8/8/5b2/8/4K2R w K - - -").getCastlingManager();
		classUnderTest.addCastlingMoves(ml);
		expectWkscMove();
	}

	@Test
	public void test_BlackQueenSideCastle() throws IllegalNotationException  {
		// 8 R...K...
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		classUnderTest = new BoardManager("r3k3/8/8/8/8/8/8/8 b q - - -").getCastlingManager();
		classUnderTest.addCastlingMoves(ml);
		expectBqscMove();
	}
	
	@Test
	public void test_BlackQueenSideCastle_Check() {
		// 8 R...K...
		// 7 ........
		// 6 ......b.
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		classUnderTest = new BoardManager("r3k3/8/6B1/8/8/8/8/8 b q - - -").getCastlingManager();
		classUnderTest.addCastlingMoves(ml);
		assertTrue(ml.isEmpty());
	}
	
	@Test
	public void test_bqsc_fen_unavaill() {
		// 8 R...K...
		// 7 ........
		// 6 ......b.
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		classUnderTest = new BoardManager("r3k3/8/8/8/8/8/8/8 b Q - - -").getCastlingManager();
		classUnderTest.addCastlingMoves(ml);
		assertTrue(ml.isEmpty());
	}
	
	@Test
	public void test_bqsc_fen_availl() throws IllegalNotationException {
		// 8 R...K...
		// 7 ........
		// 6 ......b.
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		classUnderTest = new BoardManager("r3k3/8/8/8/8/8/8/8 b q - - -").getCastlingManager();
		classUnderTest.addCastlingMoves(ml);
		expectBqscMove();
	}	
	
	@Test
	public void test_BlackQueenSideCastle_MovesThroughCheckAtD8() {
		// 8 R...K...
		// 7 ........
		// 6 .....b..
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		classUnderTest = new BoardManager("r3k3/8/5B2/8/8/8/8/8 b q - - -").getCastlingManager();
		classUnderTest.addCastlingMoves(ml);
		assertTrue(ml.isEmpty());
	}
		
	@Test
	public void test_BlackQueenSideCastle_MovesThroughCheckAtC8() {
		// 8 R...K...
		// 7 ........
		// 6 ....b...
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		classUnderTest = new BoardManager("r3k3/8/4B3/8/8/8/8/8 b q - - -").getCastlingManager();
		classUnderTest.addCastlingMoves(ml);
		assertTrue(ml.isEmpty());
	}
	
	@Test
	public void test_BlackQueenSideCastle_BlockedOwnPieceAtD8() {
		// 8 R..QK...
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		classUnderTest = new BoardManager("r2qk3/8/8/8/8/8/8/8 b q - - -").getCastlingManager();
		classUnderTest.addCastlingMoves(ml);
		assertTrue(ml.isEmpty());
	}
	
	@Test
	public void test_BlackQueenSideCastle_RookIsAttackedAtA8() throws IllegalNotationException  {
		// 8 R...K...
		// 7 ........
		// 6 R.......
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		classUnderTest = new BoardManager("r3k3/8/R7/8/8/8/8/8 b q - - -").getCastlingManager();
		classUnderTest.addCastlingMoves(ml);
		expectBqscMove();
	}
	
	@Test
	public void test_WhiteKingSideCastle_fromgame() throws IllegalNotationException  {
		classUnderTest = new BoardManager("rnb2bnr/1ppp1kpp/4pq2/8/p1BPP3/8/PPP2PPP/RNBQK2R w KQ - 1 7").getCastlingManager();
		classUnderTest.addCastlingMoves(ml);
		expectWkscMove();
	}

	private void expectBqscMove() throws IllegalNotationException {
		GenericMove expectedMove = new GenericMove("e8c8");
		GenericMove qscMove = ml.get(0);
		assertTrue(qscMove != null);
		assertTrue(expectedMove.equals(qscMove));
	}
	
	private void expectWkscMove() throws IllegalNotationException {
		GenericMove expectedMove = new GenericMove("e1g1");
		GenericMove kscMove = ml.get(0);
		assertTrue(kscMove != null);
		assertTrue(expectedMove.equals(kscMove));
	}
}
