package eubos.board;

import static org.junit.Assert.*;

import org.junit.Test;

import com.fluxchess.jcpi.models.GenericMove;
import com.fluxchess.jcpi.models.IllegalNotationException;

public class CastlingManagerTest {

	protected CastlingManager classUnderTest;
	
	@Test
	public void test_WhiteKingSideCastle() throws IllegalNotationException{
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ....k..r
		//   abcdefgh
		classUnderTest = new BoardManager("8/8/8/8/8/8/8/4K2R w - - - -").getCastlingManager();
		GenericMove kscMove = classUnderTest.getKingsideCastleMove();
		GenericMove expectedMove = new GenericMove("e1g1");
		assertTrue(kscMove != null);
		assertTrue(expectedMove.equals(kscMove));
	}
	
	@Test
	public void test_WhiteKingSideCastle_Check() throws IllegalNotationException {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ..B.....
		// 2 ........
		// 1 ....k..r
		//   abcdefgh
		classUnderTest = new BoardManager("8/8/8/8/8/2b5/8/4K2R w - - - -").getCastlingManager();
		GenericMove kscMove = classUnderTest.getKingsideCastleMove();
		assertTrue(kscMove == null);
	}
	
	@Test
	public void test_WhiteKingSideCastle_MovesThroughCheckAtF1() {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ...B....
		// 2 ........
		// 1 ....k..r
		//   abcdefgh
		classUnderTest = new BoardManager("8/8/8/8/8/3b4/8/4K2R w - - - -").getCastlingManager();
		GenericMove kscMove = classUnderTest.getKingsideCastleMove();
		assertTrue(kscMove == null);
	}
	
	@Test
	public void test_WhiteKingSideCastle_MovesThroughCheckAtG1() {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ....B...
		// 2 ........
		// 1 ....k..r
		//   abcdefgh
		classUnderTest = new BoardManager("8/8/8/8/8/4b3/8/4K2R w - - - -").getCastlingManager();
		GenericMove kscMove = classUnderTest.getKingsideCastleMove();
		assertTrue(kscMove == null);
	}
	
	@Test
	public void test_WhiteKingSideCastle_BlockedOwnPieceAtF1() {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ....kb.r
		//   abcdefgh
		classUnderTest = new BoardManager("8/8/8/8/8/8/8/4KB1R w - - - -").getCastlingManager();
		GenericMove kscMove = classUnderTest.getKingsideCastleMove();
		assertTrue(kscMove == null);
	}
	
	@Test
	public void test_WhiteKingSideCastle_BlockedOwnPieceAtG1() {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ....k.br
		//   abcdefgh
		classUnderTest = new BoardManager("8/8/8/8/8/8/8/4K1BR w - - - -").getCastlingManager();
		GenericMove kscMove = classUnderTest.getKingsideCastleMove();
		assertTrue(kscMove == null);
	}	
	
	@Test
	public void test_WhiteKingSideCastle_RookIsAttackedAtH1() throws IllegalNotationException {
		// 8 ........
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 .....B..
		// 2 ........
		// 1 ....k..r
		//   abcdefgh
		classUnderTest = new BoardManager("8/8/8/8/8/5b2/8/4K2R w - - - -").getCastlingManager();
		GenericMove kscMove = classUnderTest.getKingsideCastleMove();
		GenericMove expectedMove = new GenericMove("e1g1");
		assertTrue(kscMove != null);
		assertTrue(expectedMove.equals(kscMove));
	}
	
	
	@Test
	public void test_BlackQueenSideCastle() throws IllegalNotationException  {
		// 8 R...K...
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		classUnderTest = new BoardManager("r3k3/8/8/8/8/8/8/8 b - - - -").getCastlingManager();
		GenericMove qscMove = classUnderTest.getQueensideCastleMove();
		GenericMove expectedMove = new GenericMove("e8c8");
		assertTrue(qscMove != null);
		assertTrue(expectedMove.equals(qscMove));
	}
	
	@Test
	public void test_BlackQueenSideCastle_Check() {
		// 8 R...K...
		// 7 ........
		// 6 ......b.
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		classUnderTest = new BoardManager("r3k3/8/6B1/8/8/8/8/8 b - - - -").getCastlingManager();
		GenericMove qscMove = classUnderTest.getQueensideCastleMove();
		assertTrue(qscMove == null);
	}
	
	@Test
	public void test_BlackQueenSideCastle_MovesThroughCheckAtD8() {
		// 8 R...K...
		// 7 ........
		// 6 .....b..
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		classUnderTest = new BoardManager("r3k3/8/5B2/8/8/8/8/8 b - - - -").getCastlingManager();
		GenericMove qscMove = classUnderTest.getQueensideCastleMove();
		assertTrue(qscMove == null);
	}
		
	@Test
	public void test_BlackQueenSideCastle_MovesThroughCheckAtC8() {
		// 8 R...K...
		// 7 ........
		// 6 ....b...
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		classUnderTest = new BoardManager("r3k3/8/4B3/8/8/8/8/8 b - - - -").getCastlingManager();
		GenericMove qscMove = classUnderTest.getQueensideCastleMove();
		assertTrue(qscMove == null);
	}
	
	@Test
	public void test_BlackQueenSideCastle_BlockedOwnPieceAtD8() {
		// 8 R..QK...
		// 7 ........
		// 6 ........
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		classUnderTest = new BoardManager("r2qk3/8/8/8/8/8/8/8 b - - - -").getCastlingManager();
		GenericMove qscMove = classUnderTest.getQueensideCastleMove();
		assertTrue(qscMove == null);
	}
	
	@Test
	public void test_BlackQueenSideCastle_RookIsAttackedAtA8() throws IllegalNotationException  {
		// 8 R...K...
		// 7 ........
		// 6 R.......
		// 5 ........
		// 4 ........
		// 3 ........
		// 2 ........
		// 1 ........
		//   abcdefgh
		classUnderTest = new BoardManager("r3k3/8/R7/8/8/8/8/8 b - - - -").getCastlingManager();
		GenericMove qscMove = classUnderTest.getQueensideCastleMove();
		GenericMove expectedMove = new GenericMove("e8c8");
		assertTrue(qscMove != null);
		assertTrue(expectedMove.equals(qscMove));
	}
}
